# Proxy SSH server
proxyserver:
  address: 192.168.0.1
  port: 22
  username: user
  password: userpass
  # If privatekey is set, password will be ignored. This should be written as an absolute path.
  # privatekey: /home/username/.ssh/mykey.pem

# SSH server
internalserver:
  address: 192.168.1.1
  port: 22

# Port for localhost connection
localport: 16822
